### ISSUE TITLE
ng test fails right out of the box

### ISSUE THREAD

**Issue by theutz** [bn3t/generator-angular2-firebase-bootstrap#1]
When I run `ng test` on a fresh install of this generator, each test that's already built-in gives me the following error

    Failed: Cannot set property 'stack' of undefined
        TypeError: Cannot set property 'stack' of undefined
            at NoProviderError.set [as stack] (webpack:///~/@angular/core/src/facade/errors.js:64:31 <- src/test.ts:6511:61)
            at assignAll (webpack:///~/zone.js/dist/zone.js:704:0 <- src/test.ts:90940:29)
            at NoProviderError.ZoneAwareError (webpack:///~/zone.js/dist/zone.js:775:0 <- src/test.ts:91011:16)
            at NoProviderError.BaseError [as constructor] (webpack:///~/@angular/core/src/facade/errors.js:26:0 <- src/test.ts:6473:16)
            at NoProviderError.AbstractProviderError [as constructor] (webpack:///~/@angular/core/src/di/reflective_errors.js:53:0 <- src/test.ts:47872:16)
            at new NoProviderError (webpack:///~/@angular/core/src/di/reflective_errors.js:102:0 <- src/test.ts:47921:16)
            at ReflectiveInjector_._throwOrNull (webpack:///~/@angular/core/src/di/reflective_injector.js:994:0 <- src/test.ts:68688:19)
            at ReflectiveInjector_._getByKeyDefault (webpack:///~/@angular/core/src/di/reflective_injector.js:1031:0 <- src/test.ts:68725:25)
            at ReflectiveInjector_._getByKey (webpack:///~/@angular/core/src/di/reflective_injector.js:981:0 <- src/test.ts:68675:25)
            at ReflectiveInjector_.get (webpack:///~/@angular/core/src/di/reflective_injector.js:743:0 <- src/test.ts:68437:21)
            at TestBed.get (webpack:///~/@angular/core/bundles/core-testing.umd.js:818:0 <- src/test.ts:20075:67)
            at CompiledTemplate.proxyViewClass.AppView.injectorGet (webpack:///~/@angular/core/src/linker/view.js:152:0 <- src/test.ts:69446:45)
            at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (webpack:///~/@angular/core/src/linker/view.js:580:0 <- src/test.ts:69874:49)
            at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/DynamicTestModule/AppComponent/host.ngfactory.js:15:63)
            at CompiledTemplate.proxyViewClass.AppView.createHostView (webpack:///~/@angular/core/src/linker/view.js:108:0 <- src/test.ts:69402:21)

I have used this generator in previous apps with the same release, and this was not a problem. It seems to somehow be related to `fixture.detectChanges()` in `app.component.spec.ts`, but I can't figure it out.

**Comment by bn3t** [comment]
I must admit that I never used the test very much with this generator. The tests are right how angular-cli generated them. If you find any fix don't hesitate to pull request.

**Comment by beeman** [comment]
Bug should be fixed in zone.js 0.7.6 . Please file an issue at https://github.com/angular/zone.js if that is not the case.
https://github.com/angular/angular-cli/issues/3975#issuecomment-273351108
